### GET doctors data
GET http://localhost:4700/doctors/

### GET products data
GET http://localhost:4700/store


### POST Register a user
POST http://localhost:4700/users/register
Content-Type: application/json

{
    "name": "Test",
    "password": "pass",
    "phone": "8888888888",
    "email": "test@email.com",
    "age": 20,
    "gender": "Male"
}


### POST Login a user
POST http://localhost:4700/users/login
Content-Type: application/json

{
    "name": "Test",
    "password": "pass"
}

### GET Appointments
GET http://localhost:4700/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTNkMjQyZTE3MWMxZWVkZTJmMWJkOSIsIm5hbWUiOiJUZXN0VXNlciIsImlhdCI6MTczNzk5MzMwMH0.T6SCtEmBeEYxzgHNYh1oLiDMTTEnMBLTlFDMCGDjbw4
Curr_User_Name: TestUser


### POST Appointment addition
POST http://localhost:4700/appointments/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGJiNTdjNWU5NWY5Y2QxM2YxMWQ1NiIsIm5hbWUiOiJUZXN0IiwiaWF0IjoxNzM3MjExNzE2fQ.OKh1judfQ0AR0g3CWTM3FS2ndfnP2dttX2dTSE1liXE
Content-Type: application/json

{
  "date": "2025-01-18",
  "doctorId": "1",
  "doctorName": "Dr. Sarah Johnson",
  "email": "family.yerram@gmail.com",
  "name": "Test",
  "phone": "9120",
  "specialty": "Cardiologist",
  "symptoms": "Fever",
  "time": "11:00"
}


### Update medicine
PUT http://localhost:4700/store/6772d683c0b2ab184650a225
Content-Type: application/json

{
    "name": "Pulse Oximeter",
    "description": "Measures blood oxygen levels",
    "price": 225.99,
    "image": "https://images.unsplash.com/photo-1587552562758-c09f4736d671?auto=format&fit=crop&q=80&w=400",
    "category": "Devices"
}


### Delete Medicine
DELETE http://localhost:4700/store/6772d683c0b2ab184650a225
Content-Type: application/json
